package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgendamentoId generated by hbm2java
 */
@Embeddable
public class AgendamentoId  implements java.io.Serializable {


     private int id;
     private int funcionarioId;

    public AgendamentoId() {
    }

    public AgendamentoId(int id, int funcionarioId) {
       this.id = id;
       this.funcionarioId = funcionarioId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="funcionario_id", nullable=false)
    public int getFuncionarioId() {
        return this.funcionarioId;
    }
    
    public void setFuncionarioId(int funcionarioId) {
        this.funcionarioId = funcionarioId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgendamentoId) ) return false;
		 AgendamentoId castOther = ( AgendamentoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getFuncionarioId()==castOther.getFuncionarioId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getFuncionarioId();
         return result;
   }   


}


