package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agendamento generated by hbm2java
 */
@Entity
@Table(name="agendamento"
    ,catalog="stockmanager"
)
public class Agendamento  implements java.io.Serializable {


     private AgendamentoId id;
     private Funcionario funcionario;
     private String titulo;
     private String descricao;
     private Date data;
     private char estado;
     private char ativo;
     private Set<PessoaHasAgendamento> pessoaHasAgendamentos = new HashSet<PessoaHasAgendamento>(0);

    public Agendamento() {
    }

	
    public Agendamento(AgendamentoId id, Funcionario funcionario, Date data, char estado, char ativo) {
        this.id = id;
        this.funcionario = funcionario;
        this.data = data;
        this.estado = estado;
        this.ativo = ativo;
    }
    public Agendamento(AgendamentoId id, Funcionario funcionario, String descricao, Date data, char estado, char ativo, Set<PessoaHasAgendamento> pessoaHasAgendamentos) {
       this.id = id;
       this.funcionario = funcionario;
       this.descricao = descricao;
       this.data = data;
       this.estado = estado;
       this.ativo = ativo;
       this.pessoaHasAgendamentos = pessoaHasAgendamentos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="funcionarioId", column=@Column(name="funcionario_id", nullable=false) ) } )
    public AgendamentoId getId() {
        return this.id;
    }
    
    public void setId(AgendamentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_id", nullable=false, insertable=false, updatable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    
    @Column(name="descricao", length=65535)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data", nullable=false, length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agendamento")
    public Set<PessoaHasAgendamento> getPessoaHasAgendamentos() {
        return this.pessoaHasAgendamentos;
    }
    
    public void setPessoaHasAgendamentos(Set<PessoaHasAgendamento> pessoaHasAgendamentos) {
        this.pessoaHasAgendamentos = pessoaHasAgendamentos;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return descricao;
    }
}


