package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="stockmanager"
)
public class Cidade  implements java.io.Serializable {


     private int id;
     private String nome;
     private String uf;
     private char ativo;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Cidade() {
    }

	
    public Cidade(int id, String nome, String uf, char ativo) {
        this.id = id;
        this.nome = nome;
        this.uf = uf;
        this.ativo = ativo;
    }
    public Cidade(int id, String nome, String uf, char ativo, Set<Endereco> enderecos) {
       this.id = id;
       this.nome = nome;
       this.uf = uf;
       this.ativo = ativo;
       this.enderecos = enderecos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="uf", nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


