package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstoqueHasProdutoId generated by hbm2java
 */
@Embeddable
public class EstoqueHasProdutoId  implements java.io.Serializable {


     private int insercaoId;
     private int estoqueId;
     private int produtoId;

    public EstoqueHasProdutoId() {
    }

    public EstoqueHasProdutoId(int insercaoId, int estoqueId, int produtoId) {
       this.insercaoId = insercaoId;
       this.estoqueId = estoqueId;
       this.produtoId = produtoId;
    }
   


    @Column(name="insercao_id", nullable=false)
    public int getInsercaoId() {
        return this.insercaoId;
    }
    
    public void setInsercaoId(int insercaoId) {
        this.insercaoId = insercaoId;
    }


    @Column(name="Estoque_id", nullable=false)
    public int getEstoqueId() {
        return this.estoqueId;
    }
    
    public void setEstoqueId(int estoqueId) {
        this.estoqueId = estoqueId;
    }


    @Column(name="produto_id", nullable=false)
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstoqueHasProdutoId) ) return false;
		 EstoqueHasProdutoId castOther = ( EstoqueHasProdutoId ) other; 
         
		 return (this.getInsercaoId()==castOther.getInsercaoId())
 && (this.getEstoqueId()==castOther.getEstoqueId())
 && (this.getProdutoId()==castOther.getProdutoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInsercaoId();
         result = 37 * result + this.getEstoqueId();
         result = 37 * result + this.getProdutoId();
         return result;
   }   


}


