package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estoque generated by hbm2java
 */
@Entity
@Table(name="estoque"
    ,catalog="stockmanager"
)
public class Estoque  implements java.io.Serializable {


     private int id;
     private Endereco endereco;
     private String nome;
     private String descricao;
     private String telefone;
     private char ativo;
     private Set<EstoqueHasProduto> estoqueHasProdutos = new HashSet<EstoqueHasProduto>(0);

    public Estoque() {
    }

	
    public Estoque(int id, Endereco endereco, String nome, String descricao,String telefone, char ativo) {
        this.id = id;
        this.endereco = endereco;
        this.nome = nome;
        this.descricao = descricao;
        this.telefone = telefone;
        this.ativo = ativo;
    }
    public Estoque(int id, Endereco endereco, String nome, String descricao, String telefone, char ativo, Set<EstoqueHasProduto> estoqueHasProdutos) {
       this.id = id;
       this.endereco = endereco;
       this.nome = nome;
       this.descricao = descricao;
       this.telefone = telefone;
       this.ativo = ativo;
       this.estoqueHasProdutos = estoqueHasProdutos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco_id", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="nome", nullable=false, length=500)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", length=65535)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="telefone", nullable=false, length=25)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estoque")
    public Set<EstoqueHasProduto> getEstoqueHasProdutos() {
        return this.estoqueHasProdutos;
    }
    
    public void setEstoqueHasProdutos(Set<EstoqueHasProduto> estoqueHasProdutos) {
        this.estoqueHasProdutos = estoqueHasProdutos;
    }

    @Override
    public String toString() {
        return nome;
    }
}


