package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="stockmanager"
    , uniqueConstraints = @UniqueConstraint(columnNames="login") 
)
public class Funcionario  implements java.io.Serializable {


     private int id;
     private Pessoa pessoa;
     private String login;
     private String senha;
     private String funcao;
     private char nivelacesso;
     private String email;
     private String senhaemail;
     private char ativo;
     private Set<Insercao> insercaos = new HashSet<Insercao>(0);
     private Set<Agendamento> agendamentos = new HashSet<Agendamento>(0);

    public Funcionario() {
    }

	
    public Funcionario(int id, Pessoa pessoa, String login, String senha, String funcao, char nivelacesso, String email, String senhaemail, char ativo) {
        this.id = id;
        this.pessoa = pessoa;
        this.login = login;
        this.senha = senha;
        this.funcao = funcao;
        this.nivelacesso = nivelacesso;
        this.email = email;
        this.senhaemail = senhaemail;
        this.ativo = ativo;
    }
    public Funcionario(int id, Pessoa pessoa, String login, String senha, String funcao, char nivelacesso, String email, String senhaemail, char ativo, Set<Insercao> insercaos, Set<Agendamento> agendamentos) {
       this.id = id;
       this.pessoa = pessoa;
       this.login = login;
       this.senha = senha;
       this.funcao = funcao;
       this.nivelacesso = nivelacesso;
       this.email = email;
       this.senhaemail = senhaemail;
       this.ativo = ativo;
       this.insercaos = insercaos;
       this.agendamentos = agendamentos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_id", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="login", unique=true, nullable=false, length=85)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="senha", nullable=false, length=40)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="funcao", nullable=false, length=100)
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }

    
    @Column(name="nivelacesso", nullable=false, length=1)
    public char getNivelacesso() {
        return this.nivelacesso;
    }
    
    public void setNivelacesso(char nivelacesso) {
        this.nivelacesso = nivelacesso;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="senhaemail", nullable=false, length=45)
    public String getSenhaemail() {
        return this.senhaemail;
    }
    
    public void setSenhaemail(String senhaemail) {
        this.senhaemail = senhaemail;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set<Insercao> getInsercaos() {
        return this.insercaos;
    }
    
    public void setInsercaos(Set<Insercao> insercaos) {
        this.insercaos = insercaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set<Agendamento> getAgendamentos() {
        return this.agendamentos;
    }
    
    public void setAgendamentos(Set<Agendamento> agendamentos) {
        this.agendamentos = agendamentos;
    }




}


