package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name="marca"
    ,catalog="stockmanager"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class Marca  implements java.io.Serializable {


     private int id;
     private String nome;
     private String descricao;
     private char ativo;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Marca() {
    }

	
    public Marca(int id, String nome, char ativo) {
        this.id = id;
        this.nome = nome;
        this.ativo = ativo;
    }
    public Marca(int id, String nome, String descricao, char ativo, Set<Produto> produtos) {
       this.id = id;
       this.nome = nome;
       this.descricao = descricao;
       this.ativo = ativo;
       this.produtos = produtos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", unique=true, nullable=false, length=500)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", length=65535)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="marca")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


