package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NfeHasProduto generated by hbm2java
 */
@Entity
@Table(name="nfe_has_produto"
    ,catalog="stockmanager"
)
public class NfeHasProduto  implements java.io.Serializable {


     private NfeHasProdutoId id;
     private Nfe nfe;
     private Produto produto;
     private double quantidade;
     private double valorprodutos;
     private char ativo;

    public NfeHasProduto() {
    }

    public NfeHasProduto(NfeHasProdutoId id, Nfe nfe, Produto produto, double quantidade, double valorprodutos, char ativo) {
       this.id = id;
       this.nfe = nfe;
       this.produto = produto;
       this.quantidade = quantidade;
       this.valorprodutos = valorprodutos;
       this.ativo = ativo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nfeId", column=@Column(name="nfe_id", nullable=false) ), 
        @AttributeOverride(name="produtoId", column=@Column(name="produto_id", nullable=false) ) } )
    public NfeHasProdutoId getId() {
        return this.id;
    }
    
    public void setId(NfeHasProdutoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nfe_id", nullable=false, insertable=false, updatable=false)
    public Nfe getNfe() {
        return this.nfe;
    }
    
    public void setNfe(Nfe nfe) {
        this.nfe = nfe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_id", nullable=false, insertable=false, updatable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    
    @Column(name="quantidade", nullable=false, precision=22, scale=0)
    public double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valorprodutos", nullable=false, precision=22, scale=0)
    public double getValorprodutos() {
        return this.valorprodutos;
    }
    
    public void setValorprodutos(double valorprodutos) {
        this.valorprodutos = valorprodutos;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }




}


