package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NfeHasProdutoId generated by hbm2java
 */
@Embeddable
public class NfeHasProdutoId  implements java.io.Serializable {


     private int nfeId;
     private int produtoId;

    public NfeHasProdutoId() {
    }

    public NfeHasProdutoId(int nfeId, int produtoId) {
       this.nfeId = nfeId;
       this.produtoId = produtoId;
    }
   


    @Column(name="nfe_id", nullable=false)
    public int getNfeId() {
        return this.nfeId;
    }
    
    public void setNfeId(int nfeId) {
        this.nfeId = nfeId;
    }


    @Column(name="produto_id", nullable=false)
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NfeHasProdutoId) ) return false;
		 NfeHasProdutoId castOther = ( NfeHasProdutoId ) other; 
         
		 return (this.getNfeId()==castOther.getNfeId())
 && (this.getProdutoId()==castOther.getProdutoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNfeId();
         result = 37 * result + this.getProdutoId();
         return result;
   }   


}


