package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PessoaHasTipoId generated by hbm2java
 */
@Embeddable
public class PessoaHasTipoId  implements java.io.Serializable {


     private int pessoaId;
     private int tipoId;

    public PessoaHasTipoId() {
    }

    public PessoaHasTipoId(int pessoaId, int tipoId) {
       this.pessoaId = pessoaId;
       this.tipoId = tipoId;
    }
   


    @Column(name="pessoa_id", nullable=false)
    public int getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }


    @Column(name="tipo_id", nullable=false)
    public int getTipoId() {
        return this.tipoId;
    }
    
    public void setTipoId(int tipoId) {
        this.tipoId = tipoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PessoaHasTipoId) ) return false;
		 PessoaHasTipoId castOther = ( PessoaHasTipoId ) other; 
         
		 return (this.getPessoaId()==castOther.getPessoaId())
 && (this.getTipoId()==castOther.getTipoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPessoaId();
         result = 37 * result + this.getTipoId();
         return result;
   }   


}


