package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,catalog="stockmanager"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cnpj"), @UniqueConstraint(columnNames="cpf")} 
)
public class Pessoa  implements java.io.Serializable {


     private int id;
     private Endereco endereco;
     private String denominacaosocial;
     private String nome;
     private String email;
     private String cnpj;
     private String cpf;
     private String observacoes;
     private char ativo;
     private Set<PessoaHasAgendamento> pessoaHasAgendamentos = new HashSet<PessoaHasAgendamento>(0);
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<PessoaHasTelefones> pessoaHasTelefoneses = new HashSet<PessoaHasTelefones>(0);
     private Set<PessoaHasTipo> pessoaHasTipos = new HashSet<PessoaHasTipo>(0);
     private Set<Nfe> nfesForPessoadestId = new HashSet<Nfe>(0);
     private Set<Nfe> nfesForPessoaremId = new HashSet<Nfe>(0);

    public Pessoa() {
    }

	
    public Pessoa(int id, Endereco endereco, char ativo) {
        this.id = id;
        this.endereco = endereco;
        this.ativo = ativo;
    }
    public Pessoa(int id, Endereco endereco, String denominacaosocial, String nome, String email, String cnpj, String cpf, String observacoes, char ativo, Set<PessoaHasAgendamento> pessoaHasAgendamentos, Set<Funcionario> funcionarios, Set<PessoaHasTelefones> pessoaHasTelefoneses, Set<PessoaHasTipo> pessoaHasTipos, Set<Nfe> nfesForPessoadestId, Set<Nfe> nfesForPessoaremId) {
       this.id = id;
       this.endereco = endereco;
       this.denominacaosocial = denominacaosocial;
       this.nome = nome;
       this.email = email;
       this.cnpj = cnpj;
       this.cpf = cpf;
       this.observacoes = observacoes;
       this.ativo = ativo;
       this.pessoaHasAgendamentos = pessoaHasAgendamentos;
       this.funcionarios = funcionarios;
       this.pessoaHasTelefoneses = pessoaHasTelefoneses;
       this.pessoaHasTipos = pessoaHasTipos;
       this.nfesForPessoadestId = nfesForPessoadestId;
       this.nfesForPessoaremId = nfesForPessoaremId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco_id", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="denominacaosocial", length=90)
    public String getDenominacaosocial() {
        return this.denominacaosocial;
    }
    
    public void setDenominacaosocial(String denominacaosocial) {
        this.denominacaosocial = denominacaosocial;
    }

    
    @Column(name="nome", length=55)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="cnpj", unique=true, length=45)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="cpf", unique=true, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="observacoes", length=65535)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<PessoaHasAgendamento> getPessoaHasAgendamentos() {
        return this.pessoaHasAgendamentos;
    }
    
    public void setPessoaHasAgendamentos(Set<PessoaHasAgendamento> pessoaHasAgendamentos) {
        this.pessoaHasAgendamentos = pessoaHasAgendamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<PessoaHasTelefones> getPessoaHasTelefoneses() {
        return this.pessoaHasTelefoneses;
    }
    
    public void setPessoaHasTelefoneses(Set<PessoaHasTelefones> pessoaHasTelefoneses) {
        this.pessoaHasTelefoneses = pessoaHasTelefoneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<PessoaHasTipo> getPessoaHasTipos() {
        return this.pessoaHasTipos;
    }
    
    public void setPessoaHasTipos(Set<PessoaHasTipo> pessoaHasTipos) {
        this.pessoaHasTipos = pessoaHasTipos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoaByPessoadestId")
    public Set<Nfe> getNfesForPessoadestId() {
        return this.nfesForPessoadestId;
    }
    
    public void setNfesForPessoadestId(Set<Nfe> nfesForPessoadestId) {
        this.nfesForPessoadestId = nfesForPessoadestId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoaByPessoaremId")
    public Set<Nfe> getNfesForPessoaremId() {
        return this.nfesForPessoaremId;
    }
    
    public void setNfesForPessoaremId(Set<Nfe> nfesForPessoaremId) {
        this.nfesForPessoaremId = nfesForPessoaremId;
    }




}


