package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PessoaHasAgendamento generated by hbm2java
 */
@Entity
@Table(name="pessoa_has_agendamento"
    ,catalog="stockmanager"
)
public class PessoaHasAgendamento  implements java.io.Serializable {


     private PessoaHasAgendamentoId id;
     private Agendamento agendamento;
     private Pessoa pessoa;
     private char ativo;

    public PessoaHasAgendamento() {
    }

    public PessoaHasAgendamento(PessoaHasAgendamentoId id, Agendamento agendamento, Pessoa pessoa, char ativo) {
       this.id = id;
       this.agendamento = agendamento;
       this.pessoa = pessoa;
       this.ativo = ativo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pessoaId", column=@Column(name="pessoa_id", nullable=false) ), 
        @AttributeOverride(name="agendamentoId", column=@Column(name="agendamento_id", nullable=false) ), 
        @AttributeOverride(name="agendamentoFuncionarioId", column=@Column(name="agendamento_funcionario_id", nullable=false) ) } )
    public PessoaHasAgendamentoId getId() {
        return this.id;
    }
    
    public void setId(PessoaHasAgendamentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="agendamento_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="agendamento_funcionario_id", referencedColumnName="funcionario_id", nullable=false, insertable=false, updatable=false) } )
    public Agendamento getAgendamento() {
        return this.agendamento;
    }
    
    public void setAgendamento(Agendamento agendamento) {
        this.agendamento = agendamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_id", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }




}


