package com.yard.stockmanager.persistence.entity;
// Generated 20/10/2019 19:04:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Telefones generated by hbm2java
 */
@Entity
@Table(name="telefones"
    ,catalog="stockmanager"
)
public class Telefones  implements java.io.Serializable {


     private int id;
     private String numero;
     private char ativo;
     private Set<PessoaHasTelefones> pessoaHasTelefoneses = new HashSet<PessoaHasTelefones>(0);

    public Telefones() {
    }

	
    public Telefones(int id, String numero, char ativo) {
        this.id = id;
        this.numero = numero;
        this.ativo = ativo;
    }
    public Telefones(int id, String numero, char ativo, Set<PessoaHasTelefones> pessoaHasTelefoneses) {
       this.id = id;
       this.numero = numero;
       this.ativo = ativo;
       this.pessoaHasTelefoneses = pessoaHasTelefoneses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="numero", nullable=false, length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="telefones")
    public Set<PessoaHasTelefones> getPessoaHasTelefoneses() {
        return this.pessoaHasTelefoneses;
    }
    
    public void setPessoaHasTelefoneses(Set<PessoaHasTelefones> pessoaHasTelefoneses) {
        this.pessoaHasTelefoneses = pessoaHasTelefoneses;
    }




}


